# Site settings
title: coding heather
header-img: img/home-bg.png
email: osxgirl@mac.com
copyright_name: osxgirl
description: > # this means to ignore newlines until "baseurl:"
  ï£¿ Creative Professional learns to learn to code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: PetalSnap
github_username:  osxgirl
learn_profile: osxgirl
email_username: osxgirl@mac.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
